# Generated by Django 5.1.1 on 2024-10-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, default='libros/libro_default.jpg', null=True, upload_to='libros'),
        ),
    ]
